# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d7c992fb665919ad6de57f56b88f8ce8960363a6689ddd36b5fabd837086b1138e5af1e9bf5181703f42a93f7a0787b65ff64135e7a4d897042f9bcc09e7de2

test:
  secret_key_base: cf0db71eda8e8a7c2c150f90c7c93d5d545d1d445d183b159c1252a3069a03c396cb09d3050eef6d9e51593f212c308f4ce41a091dae3afcc4eee7aef0f47109

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
